<a href="https://colab.research.google.com/github/nityanandkore/Python-Study-Repo/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NUMPY

import numpy as np

In [ ]:
a=[3,4,5,6]
type(a)

list

In [ ]:
np.array(a)

array([3, 4, 5, 6])

In [ ]:
type(np.array(a))

numpy.ndarray

In [ ]:
a=[3,4,5,6.0]  #upcasting
type(a)

list

In [ ]:
np.array(a) #ALl element converted to decimal

array([3., 4., 5., 6.])

In [ ]:
v=np.array([[1,2,3],[3,4,5]])
v

array([[1, 2, 3],
       [3, 4, 5]])

In [ ]:
v[0]

array([1, 2, 3])

In [ ]:
v[0][0]

1

In [ ]:
v.shape

(2, 3)

In [ ]:
np.array([4,5,6,7])

array([4, 5, 6, 7])

In [ ]:
np.array([4,5,6,7],ndmin=2)  # Dimention changed to 1 to 2

array([[4, 5, 6, 7]])

In [ ]:
np.array([4,5,6,7],ndmin=20)

array([[[[[[[[[[[[[[[[[[[[4, 5, 6, 7]]]]]]]]]]]]]]]]]]]])

In [ ]:
np.array([4,5,6,7], dtype=complex)

array([4.+0.j, 5.+0.j, 6.+0.j, 7.+0.j])

In [ ]:
v=np.array([[1,2,3],[3,4]])   # number of element are not same 
v

array([list([1, 2, 3]), list([3, 4])], dtype=object)

In [ ]:
np.array([(3,4),(5,6)]) #List of tuples

array([[3, 4],
       [5, 6]])

In [ ]:
n=np.array([(3,4),(5,6)],dtype=[('a','<i4'),('b','<i2')]) #List of tuples

In [ ]:
n[0]

(3, 4)

In [ ]:
n[0][0]

3

In [ ]:
type(n[0][0])

numpy.int32

In [ ]:
type(n[0][1])

numpy.int16

In [ ]:
n=np.array([(3,4),(5,6)],dtype=[('a','<i2'),('b','<i8')]) #List of tuples

In [ ]:
type(n[0][0])

numpy.int16

In [ ]:
type(n[0][1])

numpy.int64

In [ ]:
m=np.mat([1,2,3,4])

In [ ]:
type(np.mat([1,2,3,4]))

numpy.matrix

In [ ]:
np.array(m)

array([[1, 2, 3, 4]])

In [ ]:
np.asanyarray([5,6,7,8]) #List is not array to this function converts to array

array([5, 6, 7, 8])

In [ ]:
np.asanyarray(m) #Not converting to array as matrix is subpart of array

matrix([[1, 2, 3, 4]])

In [ ]:
a=np.array([4,5,6,7,8])
a

array([4, 5, 6, 7, 8])

In [ ]:
b=a   #Swallow copy

In [ ]:
b

array([4, 5, 6, 7, 8])

In [ ]:
b[0]

4

In [ ]:
b[0]=35

In [ ]:
b

array([35,  5,  6,  7,  8])

In [ ]:
a

array([35,  5,  6,  7,  8])

In [ ]:
c=np.copy(a)  # Deep Copy

In [ ]:
c

array([35,  5,  6,  7,  8])

In [ ]:
c[0]=55

In [ ]:
c

array([55,  5,  6,  7,  8])

In [ ]:
a

array([35,  5,  6,  7,  8])

In [ ]:
np.fromfunction(lambda x,y :x==y,(3,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False]])

In [ ]:
np.fromfunction(lambda x,y :x+y,(3,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [ ]:
np.fromstring('1 3 5',sep=' ')

array([1., 3., 5.])

In [ ]:
np.fromstring('nk',sep=' ')

array([], dtype=float64)

In [ ]:
np.fromstring('nk',dtype=str,sep=' ')

ValueError: zero-valued itemsize

In [ ]:
np.fromstring('6,7',dtype=str,sep=' ')

ValueError: zero-valued itemsize

In [ ]:
np.fromstring('6,7',dtype=int,sep=',')

array([6, 7])

In [ ]:
a=[[3,4,5],[6,7,8],[6,7,9]]

In [ ]:
n=np.array(a)
n

array([[3, 4, 5],
       [6, 7, 8],
       [6, 7, 9]])

In [ ]:
n.ndim # Dimension

2

In [ ]:
n.size # total element

9

In [ ]:
n.shape # row by column

(3, 3)

In [ ]:
m=np.array([5,6,7])

In [ ]:
m.ndim

1

In [ ]:
m=np.array([[5,6,7]])

In [ ]:
m.ndim

2

In [ ]:
n.dtype

dtype('int32')

In [ ]:
range(5)

range(0, 5)

In [ ]:
range(5.0)

TypeError: 'float' object cannot be interpreted as an integer

In [ ]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [ ]:
n=np.arange(2.6,9.87,.5) #Start End and Step
n

array([2.6, 3.1, 3.6, 4.1, 4.6, 5.1, 5.6, 6.1, 6.6, 7.1, 7.6, 8.1, 8.6,
       9.1, 9.6])

In [ ]:
list(n)

[2.6, 3.1, 3.6, 4.1, 4.6, 5.1, 5.6, 6.1, 6.6, 7.1, 7.6, 8.1, 8.6, 9.1, 9.6]

In [ ]:
np.linspace(3,6,20) # Start, END and Number of element

array([3.        , 3.15789474, 3.31578947, 3.47368421, 3.63157895,
       3.78947368, 3.94736842, 4.10526316, 4.26315789, 4.42105263,
       4.57894737, 4.73684211, 4.89473684, 5.05263158, 5.21052632,
       5.36842105, 5.52631579, 5.68421053, 5.84210526, 6.        ])

In [ ]:
np.linspace(3,6,20,endpoint=False) # Excludes END 

array([3.  , 3.15, 3.3 , 3.45, 3.6 , 3.75, 3.9 , 4.05, 4.2 , 4.35, 4.5 ,
       4.65, 4.8 , 4.95, 5.1 , 5.25, 5.4 , 5.55, 5.7 , 5.85])

In [ ]:
np.linspace(3,6,20,endpoint=False,retstep=True)

(array([3.  , 3.15, 3.3 , 3.45, 3.6 , 3.75, 3.9 , 4.05, 4.2 , 4.35, 4.5 ,
        4.65, 4.8 , 4.95, 5.1 , 5.25, 5.4 , 5.55, 5.7 , 5.85]),
 0.15)

In [ ]:
np.linspace(3,6,20,axis=0)

array([3.        , 3.15789474, 3.31578947, 3.47368421, 3.63157895,
       3.78947368, 3.94736842, 4.10526316, 4.26315789, 4.42105263,
       4.57894737, 4.73684211, 4.89473684, 5.05263158, 5.21052632,
       5.36842105, 5.52631579, 5.68421053, 5.84210526, 6.        ])

In [ ]:
np.zeros((2,5,6)) #Array *ROW * COLUMN = 3D Array

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros((2,5,6,2)) #4 Dim

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0.,

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [ ]:
np.ones((2,3,4)) +1

array([[[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]],

       [[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]]])

In [ ]:
np.empty((4,5))

array([[3.        , 3.15789474, 3.31578947, 3.47368421, 3.63157895],
       [3.78947368, 3.94736842, 4.10526316, 4.26315789, 4.42105263],
       [4.57894737, 4.73684211, 4.89473684, 5.05263158, 5.21052632],
       [5.36842105, 5.52631579, 5.68421053, 5.84210526, 6.        ]])

In [ ]:
np.empty((4,5))[0][0]

3.0

In [ ]:
np.empty((2,4))

array([[  7.2,   7.2, 583.2,   7.2],
       [  7.2, 583.2, 583.2, 583.2]])

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.logspace(5.6,7.8,6) # Log of number

array([  398107.1705535 ,  1096478.19614319,  3019951.72040201,
        8317637.71102671, 22908676.5276777 , 63095734.4480193 ])

In [ ]:
np.logspace(5.6,7.8,6,base=2)

array([ 48.50293013,  65.79928491,  89.26359465, 121.09537878,
       164.27851489, 222.8609442 ])

In [ ]:
m=np.random.rand(4,5)
m

array([[0.55070537, 0.19307071, 0.10681786, 0.88433098, 0.46794179],
       [0.80739824, 0.22333333, 0.49771014, 0.60980797, 0.16383102],
       [0.87723925, 0.42988845, 0.70848433, 0.07115323, 0.15003866],
       [0.70750438, 0.74923117, 0.89971949, 0.99884611, 0.59514322]])

In [ ]:
m.reshape(10,2) 

array([[0.55070537, 0.19307071],
       [0.10681786, 0.88433098],
       [0.46794179, 0.80739824],
       [0.22333333, 0.49771014],
       [0.60980797, 0.16383102],
       [0.87723925, 0.42988845],
       [0.70848433, 0.07115323],
       [0.15003866, 0.70750438],
       [0.74923117, 0.89971949],
       [0.99884611, 0.59514322]])

In [ ]:
m.reshape(20,1) 

array([[0.55070537],
       [0.19307071],
       [0.10681786],
       [0.88433098],
       [0.46794179],
       [0.80739824],
       [0.22333333],
       [0.49771014],
       [0.60980797],
       [0.16383102],
       [0.87723925],
       [0.42988845],
       [0.70848433],
       [0.07115323],
       [0.15003866],
       [0.70750438],
       [0.74923117],
       [0.89971949],
       [0.99884611],
       [0.59514322]])

In [ ]:
m.reshape(5,4) 

array([[0.55070537, 0.19307071, 0.10681786, 0.88433098],
       [0.46794179, 0.80739824, 0.22333333, 0.49771014],
       [0.60980797, 0.16383102, 0.87723925, 0.42988845],
       [0.70848433, 0.07115323, 0.15003866, 0.70750438],
       [0.74923117, 0.89971949, 0.99884611, 0.59514322]])

In [ ]:
m.reshape(10,-1) # -1 does nothing. Based on First element it automatically converts

array([[0.55070537, 0.19307071],
       [0.10681786, 0.88433098],
       [0.46794179, 0.80739824],
       [0.22333333, 0.49771014],
       [0.60980797, 0.16383102],
       [0.87723925, 0.42988845],
       [0.70848433, 0.07115323],
       [0.15003866, 0.70750438],
       [0.74923117, 0.89971949],
       [0.99884611, 0.59514322]])

In [ ]:
m.reshape(-455,10) 

array([[0.55070537, 0.19307071, 0.10681786, 0.88433098, 0.46794179,
        0.80739824, 0.22333333, 0.49771014, 0.60980797, 0.16383102],
       [0.87723925, 0.42988845, 0.70848433, 0.07115323, 0.15003866,
        0.70750438, 0.74923117, 0.89971949, 0.99884611, 0.59514322]])

In [ ]:
np.random.rand(4,5)

array([[0.2143796 , 0.75449783, 0.76673149, 0.49740202, 0.85493599],
       [0.46797417, 0.80740505, 0.57841513, 0.83869576, 0.66181782],
       [0.3891603 , 0.72281677, 0.09470636, 0.98820469, 0.78831132],
       [0.39491948, 0.51893577, 0.03501351, 0.84916969, 0.4906104 ]])

In [ ]:
a=np.random.randint(3,8,(5,6))
a

array([[3, 5, 5, 4, 5, 7],
       [3, 5, 3, 5, 5, 4],
       [7, 5, 6, 6, 6, 6],
       [7, 3, 6, 3, 5, 4],
       [4, 7, 7, 6, 4, 7]])

In [ ]:
a[0]

array([3, 5, 5, 4, 5, 7])

In [ ]:
a[0:2]

array([[3, 5, 5, 4, 5, 7],
       [3, 5, 3, 5, 5, 4]])

In [ ]:
a[0:2,0:2]

array([[3, 5],
       [3, 5]])

In [ ]:
a>5

array([[False, False, False, False, False,  True],
       [False, False, False, False, False, False],
       [ True, False,  True,  True,  True,  True],
       [ True, False,  True, False, False, False],
       [False,  True,  True,  True, False,  True]])

In [ ]:
a[a>5]

array([7, 7, 6, 6, 6, 6, 7, 6, 7, 7, 6, 7])

In [ ]:
a[0][0]=90

In [ ]:
a

array([[90,  5,  5,  4,  5,  7],
       [ 3,  5,  3,  5,  5,  4],
       [ 7,  5,  6,  6,  6,  6],
       [ 7,  3,  6,  3,  5,  4],
       [ 4,  7,  7,  6,  4,  7]])

In [ ]:
m = np.array([[3,4,5],[5,6,7]])

In [ ]:
m

array([[3, 4, 5],
       [5, 6, 7]])

In [ ]:
n = np.array([[6,4,5],[5,6,7]])
n

array([[6, 4, 5],
       [5, 6, 7]])

In [ ]:
m+n

array([[ 9,  8, 10],
       [10, 12, 14]])

In [ ]:
m-n

array([[-3,  0,  0],
       [ 0,  0,  0]])

In [ ]:
m*n # its index wise multiplication and not matrix mupliplication

array([[18, 16, 25],
       [25, 36, 49]])

In [ ]:
m1=np.array([[0,1],[2,3]])
m1

array([[0, 1],
       [2, 3]])

In [ ]:
m2=np.array([[2,3],[1,8]])
m2

array([[2, 3],
       [1, 8]])

In [ ]:
m1*m2

array([[ 0,  3],
       [ 2, 24]])

In [ ]:
m1@m2

array([[ 1,  8],
       [ 7, 30]])

In [ ]:
m1**2

array([[0, 1],
       [4, 9]], dtype=int32)

In [ ]:
pow(m1,2)

array([[0, 1],
       [4, 9]], dtype=int32)

In [ ]:
m=np.zeros((3,4))

In [ ]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
m+2  #Elementwise broadcasting

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
n1=np.array([1,2,3,4])

In [ ]:
n1

array([1, 2, 3, 4])

In [ ]:
m

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
m+n1 # Rowwise broadcasting - Shape should be same

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [ ]:
n2=np.array([[3,4,5]]).T #Columnwise broadcasting - Transpose the array
n2

array([[3],
       [4],
       [5]])

In [ ]:
m+n2

array([[3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.]])

In [ ]:
m=np.random.rand(4,5)
m

array([[0.17578604, 0.32490372, 0.677607  , 0.78544247, 0.19943256],
       [0.54240966, 0.00401879, 0.0936559 , 0.23198759, 0.79809223],
       [0.48392379, 0.50359669, 0.74325415, 0.01776098, 0.9162548 ],
       [0.2616896 , 0.20263911, 0.66016092, 0.05219775, 0.92777874]])

In [ ]:
m1=np.random.rand(4,5).reshape(10,2)
m1

array([[0.29673125, 0.82459576],
       [0.38484304, 0.62684116],
       [0.92810761, 0.33763087],
       [0.38960656, 0.91885363],
       [0.68303738, 0.79832065],
       [0.05322909, 0.66382455],
       [0.0220321 , 0.79540854],
       [0.92257095, 0.03039294],
       [0.66642451, 0.72840503],
       [0.22792071, 0.44147166]])

In [ ]:
np.sqrt(m1)

array([[0.54473043, 0.90807255],
       [0.62035719, 0.79173301],
       [0.96338342, 0.58106013],
       [0.62418472, 0.95856853],
       [0.82646075, 0.89348791],
       [0.23071431, 0.81475429],
       [0.14843213, 0.89185679],
       [0.96050557, 0.17433571],
       [0.81634828, 0.85346648],
       [0.47741042, 0.66443334]])

In [ ]:
np.exp(m1)

array([[1.34545366, 2.28095853],
       [1.46938367, 1.87168886],
       [2.52971744, 1.40162303],
       [1.47639981, 2.50641547],
       [1.97988226, 2.2218066 ],
       [1.05467124, 1.94220621],
       [1.0222766 , 2.21534587],
       [2.51574995, 1.03085952],
       [1.94726244, 2.07177356],
       [1.25598573, 1.55499397]])

In [ ]:
np.log10(m1)

array([[-0.52763672, -0.0837589 ],
       [-0.41471636, -0.2028425 ],
       [-0.03240167, -0.47155785],
       [-0.40937374, -0.03675366],
       [-0.16555553, -0.09782264],
       [-1.27385093, -0.17794669],
       [-1.65694418, -0.09940975],
       [-0.03500022, -1.51722727],
       [-0.17624904, -0.13762706],
       [-0.64221622, -0.35509717]])

In [ ]:
np.fmod(m,m1) # Returns Reminder

array([[0.23888496, 0.30941182],
       [0.05089145, 0.26430253],
       [0.18512708, 0.26968165],
       [0.22874155, 0.50502849],
       [0.4546292 , 0.3862327 ],
       [0.01573095, 0.27274142],
       [0.01480916, 0.34423355],
       [0.63729105, 0.01757979],
       [0.04802742, 0.28184011],
       [0.14900886, 0.41295481]])